// autocomplete suggestions
export default function customCompletions(context) {
  let word = context.matchBefore(/\w*/);
  if (word.from == word.to && !context.explicit) return null;
  return {
    from: word.from,
    options: [
      // global constants
      { label: "W", type: "variable", info: "width of the game screen" },
      { label: "H", type: "variable", info: "height of the game screen" },
      {
        label: "T",
        type: "variable",
        info: "seconds since the game started",
      },
      {
        label: "MX",
        type: "variable",
      },
      {
        label: "MY",
        type: "variable",
      },
      { label: "PI", type: "constant" },
      { label: "TWO_PI", type: "constant" },
      { label: "HALF_PI", type: "constant" },
      // global functions
      {
        label: "litecanvas",
        type: "function",
        apply: "litecanvas({})",
        detail: "(settings?: object)",
        info: "initialize a litecanvas instance",
      },
      {
        label: "cls",
        type: "function",
        apply: "cls(",
        detail: "(color?: number)",
        info: "clear the game screen",
      },
      {
        label: "rect",
        type: "function",
        apply: "rect(",
        detail: "(x, y, width, height, color=0, radii?)",
      },
      {
        label: "rectfill",
        type: "function",
        apply: "rectfill(",
        detail: "(x, y, width, height, color=0, radii?)",
      },
      {
        label: "circ",
        type: "function",
        apply: "circ(",
        detail: "(x, y, radius, color=0)",
      },
      {
        label: "circfill",
        type: "function",
        apply: "circfill(",
        detail: "(x, y, radius, color=0)",
      },
      {
        label: "oval",
        type: "function",
        apply: "oval(",
        detail: "(x, y, rx, ry, color=0)",
      },
      {
        label: "ovalfill",
        type: "function",
        apply: "ovalfill(",
        detail: "(x, y, rx, ry, color=0)",
      },
      {
        label: "line",
        type: "function",
        apply: "line(",
        detail: "(x1, y1, x2, y2, color=0)",
      },
      {
        label: "linewidth",
        type: "function",
        apply: "linewidth(",
        detail: "(value)",
      },
      {
        label: "linedash",
        type: "function",
        apply: "linedash(",
        detail: "(pattern, ofsset)",
      },
      {
        label: "text",
        type: "function",
        apply: "text(",
        detail: "(x, y, text, color=3, style='normal')",
      },
      {
        label: "textfont",
        type: "function",
        apply: "textfont(",
        detail: "(fontName)",
        info: "default: sans-serif",
      },
      {
        label: "textsize",
        type: "function",
        apply: "textsize(",
        detail: "(size)",
        info: "default font size: 32",
      },
      {
        label: "textalign",
        type: "function",
        apply: "textalign(",
        detail: "(align, baseline)",
      },
      {
        label: "image",
        type: "function",
        apply: "image(",
        detail: "(x, y, image)",
      },
      {
        label: "paint",
        type: "function",
        apply: "paint(",
        detail: "(width, height, callback|array, options)",
        info: "Creates an image in offscreencanvas",
      },
      {
        label: "translate",
        type: "function",
        apply: "translate(",
        detail: "(x, y)",
      },
      {
        label: "scale",
        type: "function",
        apply: "scale(",
        detail: "(x, y)",
      },
      {
        label: "rotate",
        type: "function",
        apply: "rotate(",
        detail: "(radians)",
      },
      {
        label: "alpha",
        type: "function",
        apply: "alpha(",
        detail: "(value)",
      },
      {
        label: "fill",
        type: "function",
        apply: "fill(",
        detail: "(color)",
      },
      {
        label: "stroke",
        type: "function",
        apply: "stroke(",
        detail: "(color)",
      },
      {
        label: "push",
        type: "function",
        apply: "push()",
        detail: "",
        info: "save the rendering context",
      },
      {
        label: "pop",
        type: "function",
        apply: "pop()",
        detail: "",
        info: "restore the rendering context",
      },
      {
        label: "pal",
        type: "function",
        apply: "pal(colors?)",
        info: "set or reset the color palette",
      },
      {
        label: "ctx",
        type: "function",
        apply: "ctx()",
        detail: "(value?)",
        info: "get or set the canvas context",
      },
      {
        label: "clip",
        type: "function",
        apply: "clip(",
        detail: "(callback)",
        info: "create a clipping region based in a path (in the callback)",
      },
      {
        label: "sfx",
        type: "function",
        apply: "sfx()",
        detail: "(zzfxParams?, pitchSlide?, volumeFactor?)",
        info: "play a ZzFX sound",
      },
      {
        label: "volume",
        type: "function",
        apply: "volume(",
        detail: "(value)",
        info: "set the ZzFX global volume",
      },
      {
        label: "iskeydown",
        type: "function",
        apply: "iskeydown(",
        detail: "(key?)",
      },
      {
        label: "iskeypressed",
        type: "function",
        apply: "iskeypressed(",
        detail: "(key?)",
      },
      {
        label: "rseed",
        type: "function",
        apply: "rseed(",
        detail: "(value?)",
        info: "initialize the RNG with a seed value or get the current state",
      },
      {
        label: "rand",
        type: "function",
        apply: "rand()",
        detail: "(min=0.0, max=1.0)",
        info: "get a pseudo-random float between min (inclusive) and max (exclusive)",
      },
      {
        label: "randi",
        type: "function",
        apply: "randi()",
        detail: "(min=0, max=1)",
        info: "get a pseudo-random integer between min (inclusive) and max (inclusive)",
      },
      {
        label: "map",
        type: "function",
        apply: "map(",
        detail: "(val, min1, max1, min2, max2, withinBounds=false)",
      },
      {
        label: "norm",
        type: "function",
        apply: "norm(",
        detail: "(val, min, max)",
      },
      {
        label: "clamp",
        type: "function",
        apply: "clamp(",
        detail: "(value, min, max)",
      },
      {
        label: "wrap",
        type: "function",
        apply: "wrap(",
        detail: "(value, min, max)",
      },
      {
        label: "lerp",
        type: "function",
        apply: "lerp(",
        detail: "(start, end, t)",
        info: "linear interpolation from `start` to `end` over `t`%.",
      },
      {
        label: "deg2rad",
        type: "function",
        apply: "deg2rad(",
        detail: "(degrees)",
      },
      {
        label: "rad2deg",
        type: "function",
        apply: "rad2deg(",
        detail: "(radians)",
      },
      {
        label: "wave",
        type: "function",
        apply: "wave(",
        detail: "(from, to, t, fn)",
      },
      {
        label: "sin",
        type: "function",
        apply: "sin(",
        detail: "(radians)",
      },
      {
        label: "cos",
        type: "function",
        apply: "cos(",
        detail: "(radians)",
      },
      {
        label: "tan",
        type: "function",
        apply: "tan(",
        detail: "(radians)",
      },
      {
        label: "abs",
        type: "function",
        apply: "abs(",
        detail: "(value)",
      },
      {
        label: "ceil",
        type: "function",
        apply: "ceil(",
        detail: "(value)",
      },
      {
        label: "round",
        type: "function",
        apply: "round(",
        detail: "(value, decimals = 0)",
      },
      {
        label: "floor",
        type: "function",
        apply: "floor(",
        detail: "(value)",
      },
      {
        label: "trunc",
        type: "function",
        apply: "trunc(",
        detail: "(value)",
      },
      {
        label: "min",
        type: "function",
        apply: "min(",
        detail: "(...values)",
      },
      {
        label: "max",
        type: "function",
        apply: "max(",
        detail: "(...values)",
      },
      {
        label: "pow",
        type: "function",
        apply: "pow(",
        detail: "(a, b)",
      },
      {
        label: "sqrt",
        type: "function",
        apply: "sqrt(",
        detail: "(value)",
      },
      {
        label: "sign",
        type: "function",
        apply: "sign(",
        detail: "(value)",
      },
      {
        label: "atan2",
        type: "function",
        apply: "atan2(",
        detail: "(y, x)",
      },
      {
        label: "hypot",
        type: "function",
        apply: "hypot(",
        detail: "(x, y, ...)",
      },
      {
        label: "exp",
        type: "function",
        apply: "exp(",
        detail: "(x)",
      },
      {
        label: "timescale",
        type: "function",
        apply: "timescale(",
        detail: "(value)",
        info: "Sets the scale of the game's delta time (dt)",
      },
      {
        label: "canvas",
        type: "function",
        apply: "canvas()",
        info: "returns the canvas",
      },
      {
        label: "use",
        type: "function",
        apply: "use(",
        detail: "(pluginFunction)",
        info: "Loads a plugin to extend the litecanvas engine",
      },
      {
        label: "def",
        type: "function",
        apply: "def(",
        detail: "(name, value)",
      },
      {
        label: "listen",
        type: "function",
        apply: "listen(",
        detail: "(event, callback)",
      },
      {
        label: "emit",
        type: "function",
        apply: "emit(",
        detail: "(event, a1, a2, a3, a4)",
      },
      {
        label: "framerate",
        type: "function",
        apply: "framerate(",
        detail: "(value)",
      },
      {
        label: "stat",
        type: "function",
        apply: "stat(",
        detail: "(n)",
        info: "returns internal informations",
      },
      {
        label: "quit",
        type: "function",
        apply: "quit()",
        detail: "shutdown a Litecanvas' instance",
      },
      {
        label: "pause",
        type: "function",
        apply: "pause()",
      },
      {
        label: "resume",
        type: "function",
        apply: "resume()",
      },
      {
        label: "paused",
        type: "function",
        apply: "paused()",
      },

      // asset loader plugin
      {
        label: "loadScript",
        type: "function",
        apply: "loadScript(",
        detail: "(url, callback)",
        info: "Load a JavaScript file",
      },
      {
        label: "loadImage",
        type: "function",
        apply: "loadImage(",
        detail: "(url, callback)",
        info: "Load a image",
      },
      {
        label: "loadFont",
        type: "function",
        apply: "loadFont(",
        detail: "(name, url, callback)",
        info: "Load a font",
      },
      {
        label: "loadJSON",
        type: "function",
        apply: "loadJSON(",
        detail: "(url, callback, fetchOptions)",
        info: "Load a JSON file",
      },
      {
        label: "load",
        type: "function",
        apply: "load(",
        detail: "(callback: (resolve,reject)=>void)",
        info: "Create a custom loader",
      },
      {
        label: "LOADING",
        type: "variable",
        info: "return the amount of assets that are loading",
      },
      {
        label: "ASSETS",
        type: "variable",
        info: "list of all loaded assets",
      },
    ],
  };
}
